### ISSUE TITLE
Allow external tools to provide SLI results via events vs just via SLI-provider

### ISSUE THREAD

**Issue by grabnerandi** [keptn/enhancement-proposals#14]
# Allow external tools to provide SLI Results via Events vs just via SLI Provider

SLI results should not only be pulled in via an SLI Provider but it must be possible to push SLI Results to Keptn from tools as they are taking part of the delivery process, e.g: JMeter should be able to provide SLI Results after test execution is done via the Test Finished Event as this is the time when these values are actually available. This also eliminates writing an SLI provider to fetch data that is already available

## Motivation

When executing JMeter tests, JMeter has a lot of valuable SLI data (response time, failure rate, ...) that should be made available to the Lighthouse service to be included in SLO validation. Letting a Keptn Service or even an external tool that sends e.g: a Deployment Finished Event provide SLI Results from this tool eliminates the need to implement custom SLI providers for each potential external data source. Instead - we giving those tools the chance to provide SLI results at the time when these tools have the data available.
This eliminates the need to write specific SLI Providers for tools that are already integrated with Keptn such as the JMeter or Neoload service. This option also allows tools that integrate with Keptn, e.g: GitLabs, Jenkins ... to send key metrics via e.g: the Keptn Start Evaluation Event. Examples here would be code coverage metrics, build times, ...

While we will still need support for Multi SLI Providers I think this approach will reduce the need for multi SLI providers by a great deal as most use cases I am aware of right now are data sources such as Testing Tools. The primare SLI Provider would then be - just as it is now - the Monitoring TOol SLI PRovider

## Explanation

I propose to allow any tool to send SLIResult data as part of a cloud event. It can be the same format as our internal IndicatorValues []*SLIResult that is part of the InternalGetSLIDoneEventData

Here are a couple of scenarios
#1: Testing Tool sends metrics as part of Test Finished
JMeter can send SLIResults as part of Test Finished which are then automatically available to the Lighthouse Service, e.g: jmeter_rt_test1, jmeter_rt_test2, ...
This allows our users to use these SLIs in their SLOs without having to specify them in a custom SLI. This brings immediate value for quality gates without having to configure an SLI provider and it allows us to reuse metrics that are already available by the test execution

#2: Pipeline sends SLIs as part of the Start Evaluation Event
Jenkins can for instance send SLIResults when it starts an evaluation event, e.g: jenkins_codecoverage, jenkins_buildtime, ... 
This allows a user to include codecoverage or buildtime as part of their SLOs. This really opens a door to more data sources without having to implement new SLI Data sources for every data source

## Internal details

Internally I would simply allow tools to add SLIResult data in the Test Finished and Start Evaluation Event. Here are some example cloud events to show how this could look like for the JMeter or also the Neoload service:

```
{
  "contenttype": "application/json",
  "data": {
    "deploymentstrategy": "direct",
    "end": "2020-03-24T08:56:18Z",
    "labels": null,
    "project": "simpleproject",
    "result": "pass",
    "service": "simplenode",
    "stage": "staging",
    "start": "2020-03-24T08:43:21Z",
    "teststrategy": "performance"
    "indicatorValues": [
      {
        "metric": "jmeter_response_time",
        "success": true,
        "value": 535.624022959996
      },
      {
        "metric": "jmeter_failurerate_step1",
        "success": true,
        "value": 0.0
      },
      {
        "metric": "jmeter_failurerate_step2",
        "success": true,
        "value": 3.45
      }
    ]
  },
  "id": "3ebc02e1-bcab-40dc-a878-5868085b8016",
  "source": "jmeter-service",
  "specversion": "0.2",
  "time": "2020-03-24T08:56:18.246Z",
  "type": "sh.keptn.events.tests-finished",
  "shkeptncontext": "664d2ad3-e925-4049-a7ff-39b8e584e5b5"
}
```

Here is an example for a start evaluation that is for instance triggered by a pipeline tool
```
{
  "contenttype": "application/json",
  "data": {
    "labels": {
      "jenkinsjob" : "http://myjenkins/myproject/job/3
     "gitcommit" : "abcedefadf"
    },
    "project": "simpleproject",
    "service": "simplenode",
    "stage": "staging",
    "start": "2019-11-21T11:00:00.000Z",
    "end": "2019-11-21T11:05:00.000Z",
    "teststrategy": "performance"
    "indicatorValues": [
      {
        "metric": "jenkins_buildtime",
        "success": true,
        "value": 12400.00
      },
      {
        "metric": "jenkins_codecoverage",
        "success": true,
        "value": 33.45
      },
      {
        "metric": "jenkins_selenium_score",
        "success": true,
        "value": 75.0
      }
    ]
  },
  "id": "3ebc02e1-bcab-40dc-a878-5868085b8016",
  "source": "jenkins",
  "specversion": "0.2",
  "time": "2020-03-24T08:56:18.246Z",
  "type": "sh.keptn.event.start-evaluation",
  "shkeptncontext": "664d2ad3-e925-4049-a7ff-39b8e584e5b5",
}
```

The lighthouse service when handling the start-evaluation or the test-finished event can then take these SLIs and "merge" them with the SLIs it retrieves through the configured SLI Provider. With that the list of overall available SLIs is growing and can be used in the SLOs

## Trade-offs and mitigations

If a user references SLIs in the SLOs that is not available or was not passed by any external tool the lighthouse service needs to highlight this - but - I think it is already doing this anyway in case an SLI value is not available. 

## Breaking changes

I dont think there are any breaking changes as we are just extending the source of SLIs. Everything else we have right now will work as it works right now

## Prior art and alternatives

The alternative would be to write additional SLI providers to pull in data from other tools that have been used in the delivery process already. While this is technically feasible it is not always easy, e.g: it would be very hard for us to develop a JMEter SLI Provider becuase that SLI Provider might no longer have access to the JMEter test result file that was generated earlier. WE have no guarantee that this file still exists in that JMEter SErvice container.

## Future possibilities

Gives external tools easier access to the SLO validation by providing their own metrics as they call start-evaluation. This is a HUGE enabler of future integrations with the Quality Gate capability of keptn

**Comment by hwinkel** [comment]
This makes actually a lot of sense, We are just thinking about this as well. Specifically as the various test tool, we are speaking about network throughput tests like iperf, uperf, TRex etc. usually expose. the Results in a text format after the test run. Beside that, Prometheus or [Netdata](http://netdata.cloud) collects the typical metrics for the Resource Utilization of CPU, Memory, Network Throughput, storage IOPS etc. while testruns. Somehow this two aspects should be combined in SLO validation.

There is either the option to extend Every test tool to collect and push all test results into a Metric DB store where they can pulled from for validation. This has also a lot of benefits for comparing raw result data while evolution of the Software. However pushing the SLI directly to a uniform SLI Data endpoint would a good option.

**Comment by agardnerIT** [comment]
Close as stale?

**Comment by thschue** [comment]
Hello @grabnerandi! As discussed in the last community meeting, we follow a PR-based approach for KEPs. If this issue is still relevant to you, please create a PR. Otherwise, please close it, or we'll close this issue for you after three weeks.

**Comment by thschue** [comment]
I will close this ticket (as announced). If this EP is still interesting to you, pleasse create an PR-based enhancement proposal (PR).
