### ISSUE TITLE
Separate Dynatrace integration and Dynatrace monitoring of the cluster itself

### ISSUE THREAD

**Issue by sergiohinojosa** [keptn/enhancement-proposals#20]
Hi guys,

I believe we can make the Dynatrace integration with Keptn easier and we can separate concerns:

**UseCase Persona**:  QualityGates IT operator of Middleware Software which does not run on Kubernetes _"I want to have in my Dynatrace environment the integration with Keptn, tagging, push of events, notification but I don't want to have the OneAgent installed in my cluster or single instance with QUalityGates features due sizing or not interested in monitoring Keptn or the CI/CD pipeline"_   

Now is needed to install the two services and run the configure command to achieve this. 
 
- dynatrace-service
- dynatrace-sli-service
- keptn configure monitoring dynatrace

meaning the command "keptn configure monitoring dynatrace" should be splitted into the integration with Dynatrace (tagging, alerting, events, MZ..) and the monitoring of the Cluster itself. If we monitor the cluster we can provide the possibility also to add the Cluster and Workload monitoring. Installing and running the AG in a pod and configure it via a cloud event should be possible. 

Thanks and best
Sergio

**Comment by grabnerandi** [comment]
Hi Sergio

Very good point. But - I think there is already a solution to this problem
If you run: "keptn configure monitoring dynatrace --project=yourproject" it will not install the OneAgent on the cluster but just enable the SLI Provider for this project. Plus - the Dynatrace-Service will anyway push notifications to Dynatrace. With the latest version of the Dynatrace-Service you can also upload a dynatrace.conf.yaml which allows you to specify to which tags events shoudl be pushed

Let me know what you think and if this already implements your proposal

andi

**Comment by sergiohinojosa** [comment]
Hi Andi, 

yes, it partially does but  I would still need to configure each project I onboard (and I want all my projects to be monitored with Dynatrace). What about something like this: 

- `keptn configure monitoring dynatrace` 
> where any project I onboard will be automatically configured with Dynatrace. So I dont have to think on running this again for each quality test project I onboard) and I'm not deploying the OneAgent on the Cluster. 

- `keptn deploy monitoring dynatrace --with-workloads` 
> Here the OneAgent will be deployed and by adding --with-workloads we can even add the Cluster and CloudApps monitoring functionality.

What do you think of this approach?

**Comment by sergiohinojosa** [comment]
ahh and the `dynatrace.conf.yaml` is a very good approach, regardless of the general configuration of the service :)

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

thanks for your proposal. I'd like to redirect the concrete implementation ideas dynatrace-service and dynatrace-sli-service repository, as they are independent from Keptn itself.

What I'd like to keep as a dicussion for an enhancement proposal are the two CLI commands you suggested:

```console
keptn configure monitoring dynatrace
keptn deploy monitoring dynatrace --with-workloads
```

I believe separating the installation of monitoring and just dynatrace without monitoring (e.g., SLI provider, etc...) is the correct way to go. (Though there might be another discussion about whether oneagent should be deployed via a `keptn` command, or whether we delegate this to the user doing a `kubectl apply ...`)

**Comment by johannes-b** [comment]
A brief update on that enhancement proposal: 
- With Keptn 0.7 we also changed the behavior of the dynatrace-service to not deploy the Dynatrace OneAgent when executing `keptn configure monitoring dynatrace`. Installing the OneAgent is now a task the user has to perform manually. 

This brings us back to Sergio`s initial idea of separating concerns; namely, separating the Keptn/Dynatrace integration from the actual monitoring task. Hence, I think that this enhancement proposal is addressed and implemented.
