### ISSUE TITLE
Allow more complex JMeter Loadtests that depend on more files, enhance documentation and logging of JMeter service  

### ISSUE THREAD

**Issue by sergiohinojosa** [keptn/enhancement-proposals#21]
# Allow complex JMeter Loadtests with more files, enhance documentation and logging of JMeter service  

It would be good to allow executing more complex JMeter tests where the JMX file depends of more configuration files like a list of test users or a list of products which makes the loadtest more dynamic and robust.

Also enhancing the documentation with all the variables that are passed (like the DeploymentURI) that is mapped to SERVER_URL would be nice. 

## Internal details
The files are uploaded but not added to the JMEter container. Also by looking a the logs of the JMeter service it showed that the loadtest was executed succesfully.

```
LogLevel":"DEBUG","message":"Successfully executed JMeter test. 
```
But it was failing. Inside the container there is the JMeter.log where the execution is written. Creating the users.txt file manually in the container solved the issue.

**Comment by agardnerIT** [comment]
Close as stale?

**Comment by thschue** [comment]
Hello @sergiohinojosa! As discussed in the last community meeting, we follow a PR-based approach for KEPs. If this issue is still relevant to you, please create a PR. Otherwise, we'll close this issue after three weeks.

**Comment by thschue** [comment]
I will close this ticket (as announced). If this EP is still interesting to you, pleasse create an PR-based enhancement proposal (PR).
