### ISSUE TITLE
Gimlet - OneChart integration for Keptn

### ISSUE THREAD

**Issue by johannes-b** [keptn/enhancement-proposals#41]
# Gimlet OneChart integration for Keptn

**Success Criteria:** Keptn - by using the OneChart integration - can deploy a service without providing a Helm Chart.  

## Motivation

* *Target*:  A onechart integration provides a default Helm Chart template (aka. OneChart) that can be used to deploy a service. 

* *Pain*:  Currently, a Keptn user has to provide a Helm Chart for onboarding a service to Keptn. This Helm Chart is then deployed by Keptn.
  * Even though the chart from the [example repo](https://github.com/keptn/examples/tree/master/onboarding-carts/carts) can get re-used, in many cases the Keptn user has to adapt it.
  * The default example Helm Chart is opinionated in the way that it contains just one *Service* and *Deployment* manifest for implementing the built-in rollback functionality of Keptn.

* *Driver*: Help Keptn user to get started with Keptn and to quickly deploy the first Keptn managed service. 

## User Stories

* As a user, I deploy the `onechart-service` on the Keptn control-plane (as shown below):

```
helm install onechart-service [repo] -n keptn 
``` 

* As a user, I do not have to worry about the Helm Chart, which is used for deploying my service. In the end, I can simply do: 

```
keptn create project <my-project> --shipyard=<myshipyard.yaml>
keptn create service my-service --project=<my-project>
keptn trigger delivery --service=<my-service> --project=<my-project> --image=<image> --tag=<tag>
```

> Notes:

* *Note 1*: In Keptn <=0.8.x, you can either use the `keptn onboarding` or `keptn add-resource` commands to upload a Helm Chart for a service --> these commands become obsolete when using OneChart. 
  * [keptn onboard service](https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_onboard_service/) - this is deprecated anyways
  * [keptn add-resource](https://keptn.sh/docs/0.8.x/reference/cli/commands/keptn_add-resource/)

* *Note 2*: After implementing https://github.com/keptn/keptn/issues/3341, you can use: 
```
keptn trigger delivery --service=<my-service> --project=<my-project> --values="shipyardController.image.tag=0.8.2-dev20210222"
```

## Open Questions
- How can we handle rollbacks with OneChart?
- Are there different types/classifications of OneCharts, e.g., one for webapp, database, etc.? 
- Versioning of OneChart: How can we make sure to apply the correct version of the OneChart (in case the OneChart is not stored in the git repo maintained by Keptn).
- Should the service be called: `onechart-service` ? 

## Implementation Details

- The `onechart-service` subscribes to a `sh.keptn.event.service.create.started` and responsible for creating the Helm Chart based on the OneChart.
  - Advantage: The integration kicks in when the service is going to be created. 
  - Drawback: It may take the `onechart-service` some time to finish its job. Hence, when automation is in place that (1) creates a service and (2) immediately triggers a delivery > the Chart may not be ready yet. 

- To get started, the `keptn-service-template`: https://github.com/keptn-sandbox/keptn-service-template-go

## References
- https://gimlet.io/onechart/getting-started/

**Comment by agardnerIT** [comment]
Close as stale?
