### ISSUE TITLE
Bridge: Obfuscate sensitive data in events

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/enhancement-proposals#62]
Bridge: Obfuscate sensitive data in events

Add ability to define and obfuscate sensitive data in the bridge UI from incoming events.

## Motivation

Allow sensitive or secret data to remain secret.

This string will be visible in plain text inside the Keptn's bridge because the bridge prints out the raw event.

* Which use-cases does this KEP enable?
* Which value would this KEP create?

## Explanation

Imagine an incoming event payload contains sensitive data:

```
{
...
  "data": {
    "my-sensitive-string": "dynatrace-adam-gardner"
  }
}
```
## Internal details

Ability to define via API and UI the keys of sensitive data fields. In the above example, it would be `my-sensitive-string` then the bridge would print the event as:

```
{
...
  "data": {
    "my-sensitive-string": "*****"
  }
}
```

## Trade-offs and mitigations

N/A

## Breaking changes

N/A

## Prior art and alternatives

Alternatives:
- Use of [sealed secrets](https://aws.amazon.com/blogs/opensource/managing-secrets-deployment-in-kubernetes-using-sealed-secrets/)
- Defining secrets in Keptn's bridge and all keptn services are coded to 
Note this second option means a higher congnitive load on Keptn users and developers. It's not as user friendly.

## Open questions

N/A

## Future possibilities

N/A

**Comment by agardnerIT** [comment]
I still think this is essential.

**Comment by thschue** [comment]
Hello @agardnerIT! As discussed in the last community meeting, we follow a PR-based approach for KEPs. If this issue is still relevant to you, please create a PR. Otherwise, please close it, or we'll close this issue for you after three weeks.

**Comment by thschue** [comment]
I will close this ticket (as announced). If this EP is still interesting to you, pleasse create an PR-based enhancement proposal (PR).
