### ISSUE TITLE
Status Dashboard

### ISSUE THREAD

**Issue by agardnerIT** [keptn/enhancement-proposals#76]
# Status Dashboard

As a Keptn admin, I want to see an overview of how Keptn is used. I need a dashboard to show high level statistics.

## Motivation

* How many times was each sequence triggered?
* Which sequences are failing?
* What is my most popular project (by sequence usage)?
* How many times was each sequence triggered (split by a sequence label) - useful to cross charge teams for Keptn usage

## Explanation

This dashboard shows how Keptn has been used over the last day, week, month etc. It shows which sequences are being triggered and I can see sequences split by any provided label.

## Internal details

Create a dashboard which is driven by the cloud event stats that are already available.

**Comment by agardnerIT** [comment]
I still think this is valuable. A grafana dashboard with these stats for example.

**Comment by thschue** [comment]
Hello @agardnerIT! As discussed in the last community meeting, we follow a PR-based approach for KEPs. If this issue is still relevant to you, please create a PR. Otherwise, please close it, or we'll close this issue for you after three weeks.
