### ISSUE TITLE
Open Policy Agent for Sequences

### ISSUE THREAD

**Issue by agardnerIT** [keptn/enhancement-proposals#77]
Open Policy Agent for Sequences

Integrate OPA for expanded sequence control.

## Motivation

* Sequences are only allowed to run between certain times
* Sequences can only be run by certain users
* Sequences can only be run if they contain certain labels.
* etc

**Comment by agardnerIT** [comment]
I still think this is valid and useful @bradmccoydev - do you know anyone that could work on this with me?

**Comment by bradmccoydev** [comment]
I have experience in OPA. We can work with a student on it maybe and help them here and there as I can't commit to working on it much.  My first question is how do we get this as JSON to pass through OPA

**Comment by thschue** [comment]
Hello @agardnerIT! As discussed in the last community meeting, we follow a PR-based approach for KEPs. If this issue is still relevant to you, please create a PR. Otherwise, we'll close this issue after three weeks.

**Comment by thschue** [comment]
I will close this ticket (as announced). If this EP is still interesting to you, pleasse create an PR-based enhancement proposal (PR).
