### ISSUE TITLE
Reference / Pinned Evaluations

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/enhancement-proposals#80]
# Reference / Pinned Evaluations

This KEP proposes the ability to mark an evaluation as the "reference" evaluation against which all future evaluations for that project + service + stage would be measured.

## Motivation

I run lots of evaluations, some pass and others fail due to factors outside my control. But eventually I get everything "just so" and I know that evaluation `123` from the 18th April at 10:34 was "perfect" and so I want all future evaluations to be compared against that specific evaluation - rather than any average or previous results.

## Explanation

This KEP would allow us to say, in effect, compare all future evaluations against the results of this specific evaluation, until I tell you (Keptn) otherwise.

**Comment by agardnerIT** [comment]
I still think this is relevant.

**Comment by thschue** [comment]
Hello @agardnerIT! As discussed in the last community meeting, we follow a PR-based approach for KEPs. If this issue is still relevant to you, please create a PR. Otherwise, we'll close this issue after three weeks.

**Comment by thschue** [comment]
I will close this ticket (as announced). If this EP is still interesting to you, pleasse create an PR-based enhancement proposal (PR).
