### ISSUE TITLE
KEP-84 - Reliable Usage Analytics collection

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/enhancement-proposals#84]
# Keptn Usage Analytics Engine

Summarizes the proposal for having a new analytics engine for gathering usage 

## Motivation

It would be nice to know basics about Keptn usage, and for that we would need to extend the current usage analytics collection and the implementation. It includes installation numbers, service usage statistics, feature flags, etc.

## Internal details

Currently we rely on the update checks that poll a pre-defined URL to retrieve the data for CLI and Keptn Bridge. When collecting usage analytics is enabled, Keptn and CLI will check for updates. This is opt-in for Keptn Bridge and opt-out for Keptn CLI at the moment. These URLs are served by AWS CloudFront, and then we retrieve access logs and parse them with the scripts. This engine is to be reworked (see below). The request is logged in the format shown here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html

The following data is collected at the moment:

- IP address;
- Version of Keptn deployment;

The following data *CAN* be collected according to the reference page:

- IP address;
- Version of Keptn deployment;
- Number of projects, stages, and services;
- Number of root events per service and day;
- List of installed Keptn-services including version thereof. 

## Explanation

1. The current analytics engine is not reliable. The lack of a way to uniquely identify the instance ID is the biggest problem. Right now we rely on Cloud Front logs, so we cannot say for sure how many instances are used behind a single network
    - Proposal: Introduce uniqueId as a part of Keptn core. It should be persisted in the database and retained between restarts. The recipient side and processing scripts also need to be reworked to support unique ID, likely through the HTTP URL parameter. 
    - Maybe it requires another endpoint, like Bitly Enterprise
2. The number of installations is not enough for decision making. We need to collect more data. Actually, the current analytics opt-in permissions in the Web UI allows for more data:
    - List of submitted data: https://keptn.sh/docs/0.16.x/bridge/load_information/
    - Proposal: Implement the submitted data. It requires a fresh new analytics engine. There are many open source projects like Matomo, but maybe a simple database provider + GrimoireLab are a better solution for flexibility purposes. Sentry could be used as receiver/visualization tool && has open source sponsorship
3. Since the core patches are needed, it will take several months to propagate new analytics implementation. It has to taken into account
4. Linux Foundation has strict usage analytics rules that put many limits on what cannot be submitted. E.g. Usage analytics should be opt-in, and that there should be no personal or company identifiable data in public layouts. Also note all analytics engines should comply with GDPR and the Californian equivalent

## Related problems

- Keptn CLI likely submits the usage analytics by default (opt-out), even for Cloud Automation

## References:

- Keptn 0.16 usage analytics:  https://keptn.sh/docs/0.16.x/bridge/load_information/
- LF Telemetry and Usage Analytics guidelines: https://www.linuxfoundation.org/telemetry-data-policy/

## Trade-offs and mitigations

* What are some (known) drawbacks? 
* What are some ways that they might be mitigated?

Note that mitigations do not need to be complete *solutions* and they do not need to be accomplished directly through your proposal. A suggested mitigation may even warrant its own KEP.

## Breaking changes

- Keptn CLI will stop submitting data by default on update checks
- *TBD:* Extending the list of the collected data, if needed, will require re-agreeing to the usage analytics submission.

## Prior art and alternatives

- Good and fresh comparison of open source analytics tools: https://posthog.com/blog/best-open-source-analytics-tools

## Open questions

- Technical choice for the analytics engine
- What data we want to collect? Comments with the requirements are welcome

## Future possibilities

Decision making on what's next for Keptn, community stats

**Comment by agardnerIT** [comment]
@StackScribe you moved this to done. Can the issue therefore be closed? Issues aren't auto-closed when moved to done. I don't know if that can be automated? It would make sense.

**Comment by thisthat** [comment]
Yes, we can close this since we have scarf in place .
